name: Build and Publish to GHCR
on: ["push"]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Repository Owner and Name
        id: repo_info
        run: |
          echo "OWNER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)" >> $GITHUB_ENV
          echo "REPO=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV
        shell: bash

      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.OWNER }}/${{ env.REPO }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}

      - name: Install GitHub CLI
        uses: cli/cli@v2.22.1
        with:
          version: latest

      - name: Make Docker Image Public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Encode the repository name for URL
          REPO_ENCODED=$(echo "${{ github.repository }}" | sed 's|/|%2F|g')

          # Update package visibility to public
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            "/user/packages/container/${REPO_ENCODED}/visibility" \
            -f visibility=public

      - name: Verify Image Visibility
        run: |
          echo "Verifying that the image is public..."
          curl -s -o /dev/null -w "%{http_code}" https://ghcr.io/${{ env.OWNER }}/${{ env.REPO }}:latest
          echo "Image is public and accessible."
