name: Docker Image Creation
on: [push]
jobs:
  build:
    runs-on: large-runner
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set short git commit SHA
        id: short_sha
        run: |
          echo "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: aihero/${{ github.event.repository.name }}:${{ env.SHORT_SHA }}
          cache-from: type=registry,ref=aihero/${{ github.event.repository.name }}:buildcache
          cache-to: type=registry,ref=aihero/${{ github.event.repository.name }}:buildcache,mode=max
